# JBoss7 with deployed tracee-examples-jaxws and tracee-examples-ejb
#
# VERSION       1.0

FROM mongodb
MAINTAINER Daniel Wegener "daniel.wegener@holisticon.de"

CMD ["mongod","--smallfiles", "--rest", "--noprealloc"]
